# Generated by Django 6.0.1 on 2026-02-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attacthment',
            field=models.FileField(blank=True, upload_to='email_attachments'),
        ),
    ]
