# Generated by Django 6.0.1 on 2026-01-18 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_coustomer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coustomer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='coustomer_name',
            new_name='customer_name',
        ),
    ]
